### PR TITLE
feat: add features in table

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by astagi** [comment]
Thank you @rawmain , my bad for the first repository, just a typo for the second one! Now they're fixed!

**Comment by rawmain** [comment]
> Thank you @rawmain , my bad for the first repository, just a typo for the second one! Now they're fixed!

You're welcome @astagi & thanks.

Meanwhile, DgcReader v2.1.0 has been fully merged/released a few hours ago by @DevTrevi . Now such library is aligned with DGC-SDK 1.1.1 updates (_booster scanmode & PV recovery_) too.

`| [DgcReader](https://github.com/DevTrevi/DgcReader) | .NET / .NET Framework | 07/12/2021 | ✅<br>Da v1.3.0 | ✅<br>Da v2.0.0 | ✅<br>Da v2.1.0 |`

At the present time, only the Hrnext Java/Spring library is lagging behind with updates (_not aligned yet with DGC-SDK 1.1.0-1.1.1_), but I suppose @marcoserafini2 will resume activities after current holidays.

**Comment by astagi** [comment]
@rawmain thank you! changed! Yes, @marcoserafini2 is working on updates.

I'll wait for @ministerosalute approval before merging, then I'll notify remaining SDK maintainers to rebase their onboarding branches.

**Comment by ministerosalute** [comment]
Thanks @astagi e @rawmain for the precious contributions!

**Pull request merged**
